# Generated by Django 5.2.4 on 2025-07-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='0000', max_length=20),
            preserve_default=False,
        ),
    ]
